# Generated by Django 4.2 on 2024-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=100)),
                ("wiki", models.URLField()),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("track", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
