# Generated by Django 4.2 on 2024-02-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iGEMResearcher", "0002_reference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reference",
        ),
    ]
