# Generated by Django 4.2 on 2024-02-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iGEMResearcher", "0003_delete_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="summary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
